### ISSUE TITLE
is possible to apply in resources? 

### ISSUE THREAD

**Issue by juztinlazaro** [anantab/serverless-plugin-ifelse#12]
Hi i want to ignore dynamodb local, is this possible? thanks

```
serverlessIfElse:
  - If: '"${self:provider.stage}" == "local"'
    Exclude:
      - resources.dynamodbLocal
```
