### ISSUE TITLE
Set stage based on environment variable

### ISSUE THREAD

**Issue by hbarcelos** [anantab/serverless-plugin-ifelse#21]
I'm combining the use of this plugin with `serverless-dotenv-plugin`.
`ifelse` is declared AFTER `dotenv`:

```yaml
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-plugin-ifelse
```

Then  I have the following:

```yaml
  chainId: ${env:CHAIN_ID, "42"}
  serverlessIfElse:
    - If: '"${self:custom.chainId}" == "1"'
      Set:
        provider.stage: mainnet
      ElseSet:
        provider.stage: kovan
```

Even though the following line is logged when I run `serverless deploy`,

```
> Serverless: serverless-plugin-ifelse - Value Changed for : provider.stage to: mainnet
```
the stack created use `kovan` as the value set, as the CloudFormation template contains things like:

```json
    "HelloLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/linguo-bot-kovan-hello"
      }
    },
```

So basically even though the plugin says it changed the `stage` value, it has no effect.

**Comment by heeksfred** [comment]
I have the same problem. This plugin does not seem to set any attributes correctly.

I am trying to set one of two lifecycle policies on S3 by using this plugin:

`custom:
    archiveStatus: undefined
    nonArchiveStatus: undefined
    serverlessIfElse:
        - If: '"£{self:provider.willArchive}" == "true"'
          Set:
            custom.archiveStatus: Enabled
            custom.nonArchiveStatus: Disabled
          ElseSet:
            custom.archiveStatus: Disabled
            custom.nonArchiveStatus: Enabled`

and in the lifecycle, the status is picking up the newly set attributes:

`                LifecycleConfiguration:
                    Rules:
                        - Id: DeleteAfterTime
                          Status: £{self:custom.nonArchiveStatus}
                          Prefix: £{self:provider.archiveFolder}
                          ExpirationInDays: !Ref GlacierLifeCycleExpirationInDays

                        - Id: TransitionToGlacier
                          Status: £{self:custom.archiveStatus}
                          Prefix: £{self:provider.archiveFolder}
                          ExpirationInDays: !Ref GlacierLifeCycleExpirationInDays
                          Transitions:
                            - TransitionInDays: !Ref GlacierLifeCycleTransitionInDays
                              StorageClass: Glacier`

Even though the console log shows that the attributes have changed:

`Serverless: serverless-plugin-ifelse - Value Changed for : custom.archiveStatus to: Disabled
Serverless: serverless-plugin-ifelse - Value Changed for : custom.nonArchiveStatus to: Enabled`

The stack fails as the attributes haven't changed:

`  Serverless Error ---------------------------------------
  An error occurred: Warehouse - Status undefined is not in [Enabled, Disabled].`

**Comment by vdarevskOTF** [comment]
I am observing the same issue: 
```
custom:
  paramstage: ${self:provider.stage}

  serverlessIfElse:
    - If: '"${opt:stage, self:provider.stage}" == "local"'
      Set:
        custom.paramstage: 'dev'
      ElseSet:
        custom.paramstage: ${self:provider.stage}
```


which when printed resolves correctly, however, the values are not applied to custom.paramstage and the end result is that the value of the custom.paramstage  is always it was initially set to

 ```
paramstage: local
  serverlessIfElse:
    - If: '"local" == "local"'
      Set:
        custom.paramstage: dev
      ElseSet:
        custom.paramstage: local
```
