### ISSUE TITLE
Regex pattern with if condition not working as expected

### ISSUE THREAD

**Issue by iamyogeshg** [anantab/serverless-plugin-ifelse#29]
Hi there,

My requirement is to exclude a certain function from all stages where stage name does not end with shrd. I am doing it in the way as shown below. Using version 1.0.7 and node version is 12.22.1.

```
serverlessIfElse:
      - If: '"${self:custom.stage}" != "(*shrd)"'
        Exclude:
          - functions.LogArchiver
```

What's happening is that even in stage matching with "*shrd" pattern, plugin is excluding that function. Please advise.

Thanks
Yogesh
