### ISSUE TITLE
Unable to remove plugin

### ISSUE THREAD

**Issue by drorweiss-did** [anantab/serverless-plugin-ifelse#32]
I have a use-case to remove a plugin based on stage level.

For example, I don't want to bundle when in "local" stage:

```yaml
plugins:
  - serverless-plugin-ifelse
  - serverless-bundle
  - serverless-offline

custom:
  serverlessIfElse:
    - If: '"${self:custom.stage}" == "local"'
      Exclude:
        - plugins.1
```

However, bundling does happen.

Is this use-case valid to implement?
