### ISSUE TITLE
Can Plugin Set custom Variables?

### ISSUE THREAD

**Issue by rpattcorner** [anantab/serverless-plugin-ifelse#35]
Been experimenting, and it looks like this most useful plugin can target a section of serverless.yml like a provider, but cannot set the value of a custom variable, e.g.
```
serverlessIfElse:
    - If: '"${self:custom.somevalue}" == "true"'
      Set: 
        self:custom.targetValue: somevalue
      ElseSet:
         self:custom.targetValue: someOthervalue
```
Tried a few syntactic variants with $ and brackets, without effect

Is it indeed not possible to set a conditional custom variable this way?
Works great targeting a provider, though :)

**Comment by deCodeIt** [comment]
I did use it to **update** the custom variable value and it worked for me.

I'd the following:

```
custom:
  dynamodb:
    start:
      dbPath: "somePath/"
```

and then I used the following and it worked for my case.
```
serverlessIfElse:
  - If: '"${self:custom.ENV.IS_OFFLINE}" == "1"'
      Set:
        custom.dynamodb.start.dbPath: "someOtherPath/"
```

**Comment by CaioF** [comment]
From my experience using serverlessIfElse to set custom vars, specially those that are in the config of another plugin does not work.

**Comment by sshakyaUR** [comment]
Any update on this? I'm trying to use this `serverlessIfElse` plugin to set the cpu and memory for my fargate task (using the serverless-fargate plugin) with custom variables . the deployment logs shows it is updating the custom variables correctly but the fargate task doesn't have the updated settings.

I'm doing something like this :
```
custom:
...
    fargateMemory: ${param:fargateMemory, '2GB'}
    fargateCpu: ${param:fargateCpu, 1024}
    serverlessIfElse:
      - If: '"${param:profile}" == "dev"'
        Set:
          fargate.memory: '8GB'
          fargate.cpu: 4096
        ElseSet:
          fargate.memory: '2GB'
          fargate.cpu: 1024
   
fargate:
...
  memory: ${self:custom.fargateMemory}
  cpu: ${self:custom.fargateCpu}
```
