### ISSUE TITLE
Feature Request: support ElseIf

### ISSUE THREAD

**Issue by aniham** [anantab/serverless-plugin-ifelse#5]
Very neat plugin!  Are there any plans to add ElseIf as in:

```bash
- If: '"${self:custom.stage}" == "prod"'
  Set:
   - someVal: 'prod'
- ElseIf: '"${self:custom.stage}" == "stg"'
  Set:
  - someVal: 'stg'
- Else:
  Set:
  - someVal: 'other'
```

**Comment by GurpreetSingh5** [comment]
Any updates on this? This feature would be quite handy.

**Comment by anantab** [comment]
The plugin does not support ElseIf, but it can be achieved by writing multiple If conditions.  Eg
```
- If: '"${self:custom.stage}" == "prod"'
  Set:
    someVal: 'prod'
- If: '"${self:custom.stage}" == "stg"'
  Set:
    someVal: 'stg'
- If: '["prod","stg"].indexOf("${self:custom.stage}") == -1 '
  Set:
    someVal: 'dev'
```
