### ISSUE TITLE
How to write nested If using this ? Is this feature avalaible yet ?

### ISSUE THREAD

**Issue by GurpreetSingh5** [anantab/serverless-plugin-ifelse#8]
How to write nested If using this? Is this feature available yet?
I want to check multiple nested conditions?

**Comment by anantab** [comment]
> How to write nested If using this? Is this feature available yet?
> I want to check multiple nested conditions?

You can easily achieve nested conditions by writing multiple if conditions. Eg
```
- If: '"${self:custom.currentStage}" == "dev"'
        Set:
          provider.profile: dev
- If: '"${self:custom.currentStage}" == "test"'
        Set:
          provider.profile: test
- If: '"${self:custom.currentStage}" != "dev" && ${self:custom.currentStage}" != "test"'
        Set:
          provider.profile: prod

```
